GET https://demo-api-nh17.onrender.com/

###

POST https://demo-api-nh17.onrender.com/product
Content-Type: application/json
{
    "name": "Xyz",
    "price": 500
}

###

GET https://demo-api-nh17.onrender.com/products